columns:
  - Age: int64
  - Gender: object
  - Region: object
  - Smoking_History: object
  - Diabetes_History: object
  - Hypertension_History: object
  - Cholesterol_Level: float64
  - Physical_Activity: object
  - Diet_Quality: object
  - Alcohol_Consumption: object
  - Stress_Levels: float64
  - BMI: float64
  - Heart_Rate: float64
  - Systolic_BP: float64
  - Diastolic_BP: float64
  - Family_History: object
  - Heart_Attack_Occurrence: object
